config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get 'about' => 'static_pages#about'
  get 'portfolio' => 'static_pages#portfolio'
  resources :articles

  
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	http_basic_authenticate_with name: "pdeschamps", password: "spiderman", only: [:create, :destroy, :edit]

	 def index
       @articles = Article.all
     end

    
 
     def show
        @article = Article.find(params[:id])
        @articles = Article.all
        respond_to do |format|
        format.html  #show.html.erb
        format.json { render json: @article }
      end
     end
 
    def new
        @article = Article.new
        respond_to do |format|
        format.html #new.html.erb
        format.json { render json: @article }
       end
    end

     def edit
       @article = Article.find(params[:id])
     end

	def create
      @article = Article.new(article_params)
      respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Announcement was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        
      end
    end
  end
 
    
    

    def update
       @article = Article.find(params[:id])
 
       if @article.update(article_params)
         redirect_to @article
       else
         render 'edit'
       end
    end

    def destroy
       @article = Article.find(params[:id])
       @article.destroy
 
       redirect_to articles_path
    end

   

    private
      def article_params
        params.require(:article).permit(:title, :text)
      end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  

  def index
  end

  def about
  end 

  def portfolio
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/articles/admin.html.erb
<h1>Listing Articles</h1>
<%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      
    </tr>
  <% end %>
</table>

app/views/articles/edit.html.erb
<div class="container">
<h1>Editing article</h1>
 
<%= form_for :article, url: article_path(@article), method: :patch do |f| %>
 
  
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text, class: 'form-control form' %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', articles_path %>

<%= link_to 'Destroy', article_path(@article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
</div>

<script type="text/javascript">
  $(document).ready(function(){

    $('.form').each(function(i, elem) {
      $(elem).wysihtml5();
    });

  })
</script>

app/views/articles/index.html.erb
<body id="blog">
<div class="blog-header">

	
	<h1 class="port-text">Blog</h1>
	
</div>

<div class="col-md-7 blog_box" style="padding-bottom:5px; padding-top:5px;">
  <h1 >Blog Roll</h1>
      <hr>
   <% @articles.each do |article| %>
      <h3><%= link_to article.title, article %></h3>
      <hr>
   <% end %>

</div>

<div class="col-md-3 sidebox">
	<h1 >Palermo Deschamps</h1>
	<%= image_tag "graphicblue.png", :class => "mugshotblog" %>
	<center style="margin-top:12px;">
	<a href="https://twitter.com/palermo_tweets"><i class="fa fa-twitter-square fa-lg"></i></a>
	<a href="https://github.com/PalermoD"><i class="fa fa-github-square fa-lg whitehub"></i></a>
	<a href="https://www.linkedin.com/in/palermod"><i class="fa fa-linkedin-square fa-lg "></i></a>
	<a href=".google.com/u/0/+PalermoDeschamps"><i class="fa fa-google-plus-square fa-lg"></i></a>
	<p >palermo.deschamps@gmail.com</p>
	</center>
</div>

</body>

app/views/articles/new.html.erb
<div class="container">
 <h1>New Blog Post</h1>
<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text, class: 'form-control form'%>
  </p>
 
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', articles_path %>

</div>



<script type="text/javascript">
  $(document).ready(function(){

    $('.form').each(function(i, elem) {
      $(elem).wysihtml5();
    });

  })
</script>

app/views/articles/show.html.erb
<body id="blog">
<div class="about-header">

	
	<h1 class="port-text"><%= @article.title %></h1>
	
</div>



<div class="col-md-7 col-xs-12 blog_box">

  <div >
      <h2><%= @article.title %></h2>
      <h5>By Palermo Deschamps</h5>
      <!-- Go to www.addthis.com/dashboard to customize your tools -->
      <div class="addthis_sharing_toolbox"></div>
     
      <p class="blog_text"><%= raw(@article.text) %></p>
     
  </div>
  <div class="fb-comments col-md-12" data-href="http://www.pdeschamps.com/articles/<%= @article.id %>" data-numposts="5"></div>
</div>
</div>

<div class="col-md-3 sidebox">
	<h1>Palermo Deschamps</h1>
	<%= image_tag "graphicblue.png", :class => "mugshotblog" %>
	<center style="margin-top:12px;">
	<a href="https://twitter.com/palermo_tweets"><i class="fa fa-twitter-square fa-lg"></i></a>
	<a href="https://github.com/PalermoD"><i class="fa fa-github-square fa-lg whitehub"></i></a>
	<a href="https://www.linkedin.com/in/palermod"><i class="fa fa-linkedin-square fa-lg "></i></a>
	<a href=".google.com/u/0/+PalermoDeschamps"><i class="fa fa-google-plus-square fa-lg"></i></a>
	<p>palermo.deschamps@gmail.com</p>
	</center>
</div>

<div class="col-md-3 sidebox2">
	<h1>Blog Roll</h1>
	
	<% @articles.each do |article| %>
      <h4><%= link_to article.title, article %></h4>
   <% end %>
</div>

<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-561d19ed2311e169"></script>


</body>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
          <%= link_to "{ PD }", root_path, id: "logo" %></i> 
    </div>
        
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
         
          
          <li><%= link_to " Portfolio", portfolio_path, :class => 'fa fa-picture-o link' %></li>
          <li><%= link_to " Blog", {controller: 'articles'}, :class => 'fa fa-book link' %></li>
          
        
      </ul>
    </div>
  </div>
</header> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Palermo Deschamps</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  
</head>
<body id="content">
<div id="fb-root"></div>

<%= render 'layouts/header' %>


<%= yield %>
<%= link_to root_path do %>
	<%= image_tag "home-icon.png", :class => "corner-logo" %>
<% end %>





</body>
</html>

app/views/static_pages/about.html.erb
<div class="about-header">

	
	<h1 class="port-text">Palermo Deschamps</h1>
	<h2 class="port-text" style="font-size:35px;">coder + designer + writer</h2>
</div>

<div class="col-md-8 about_box">
	<h1>About</h1>
	
	<p class="about_text">
		 On my off time I am usually at a tech meetup, or building out an idea in the latest and most popular technologies, at the moment that's react. I have an obsession with learning new things and solving tough problems. An example of my dedication was when I worked at sequel media and was tasked to rebuild the entire platform in a stack I never worked in, and was able to do so in a few months handling the devops, backend, database, and front-end improving performance and cutting down server costs from $5000 to $200. 
	</p>
	<p class="about_text">
		I am up to date on best practices and terms and I’m fast and efficient. I am incredibly organized and very detail oriented; I rarely make errors and know what even a small mistake can mean to a project. I am also a thorough communicator and work well as part of a team in addition to my ability for self-direction.
	</p>
	<p class="about_text">
		I've studied marketing, art, design, and can work comfortably throughout most stacks or learn them quickly. I have built my own startups in the past and understand business logic as it relates to what we are building and why. In short I'm a software engineer with a passion for building awesome and beautiful things.
	</p>

	<h3>Tech</h3>
	<p class="about_text">
		Ruby - Javascript - PHP - Ruby on Rails - Sinatra - Node - Express - React - Backbone - Angular - Laravel - HTML - CSS - SASS - Git - Mysql - Postgresql - Mongo - AWS - Devops 
	</p>
    
	
</div>

<div class="col-md-3 sidebox">
	<h1 >Palermo Deschamps</h1>
	<%= image_tag "graphicblue.png", :class => "mugshotblog" %>
	<center style="margin-top:12px;">
	<a href="https://twitter.com/palermo_tweets"><i class="fa fa-twitter-square fa-lg"></i></a>
	<a href="https://github.com/PalermoD"><i class="fa fa-github-square fa-lg whitehub"></i></a>
	<a href="https://www.linkedin.com/in/palermod"><i class="fa fa-linkedin-square fa-lg "></i></a>
	<a href=".google.com/u/0/+PalermoDeschamps"><i class="fa fa-google-plus-square fa-lg"></i></a>
	<p >palermo.deschamps@gmail.com</p>
	</center>
</div>

app/views/static_pages/index.html.erb
<div class="about-header">

	
	<h1 class="port-text">Palermo Deschamps</h1>
	<h2 class="port-text" style="font-size:35px;">coder + designer + writer</h2>
</div>

<div class="col-md-8 about_box">
	<h1>Hello</h1>
	
	<p class="about_text">
		 My name is Palermo Deschamps and I am a full stack web developer based in New York City. I passionately move pixels and lines of code to craft clean, responsive, and user-friendly websites. My current weapons of choice are Javascript, React, Redux, Ruby on Rails, Node, Bootstrap, and Postgresql. Being both an engineer and designer, I help clients bring their ideas into reality. Contact me today and I would love to hear about your business
	</p>
	<p class="about_text">
		I am up to date on best practices and terms and I’m fast and efficient. I am incredibly organized and very detail oriented; I rarely make errors and know what even a small mistake can mean to a project. I am also a thorough communicator and work well as part of a team in addition to my ability for self-direction.
	</p>
	<p class="about_text">
		I've studied marketing, art, design, and can work comfortably throughout most stacks or learn them quickly. I have built my own startups in the past and understand business logic as it relates to what we are building and why. In short I'm a software engineer with a passion for building awesome and beautiful things.
	</p>

	<h3>Tech</h3>
	<p class="about_text">
		Javascript - PHP - Ruby on Rails - Sinatra - Node - Express - React - Redux - Flux - Backbone - Angular - Laravel - HTML - CSS - SASS - Git - Mysql - Postgresql - Mongo - AWS - Digital Ocean 
	</p>

	<h3>Contact</h3>
	<p class="about_text">

		The best way to get in touch with me is through my email palermo.deschamps@gmail.com 

	</p>

    
	
</div>

<div class="col-md-3 sidebox">
	<h1 >Palermo Deschamps</h1>
	<%= image_tag "graphicblue.png", :class => "mugshotblog" %>
	<center style="margin-top:12px;">
	<a href="https://twitter.com/palermo_tweets"><i class="fa fa-twitter-square fa-lg"></i></a>
	<a href="https://github.com/PalermoD"><i class="fa fa-github-square fa-lg whitehub"></i></a>
	<a href="https://www.linkedin.com/in/palermod"><i class="fa fa-linkedin-square fa-lg "></i></a>
	<a href=".google.com/u/0/+PalermoDeschamps"><i class="fa fa-google-plus-square fa-lg"></i></a>
	<p >palermo.deschamps@gmail.com</p>
	</center>
</div>

app/views/static_pages/portfolio.html.erb
<style>
	p {
		margin-top:20px !important;
		padding: 5px;
	}
</style>


<div class="port-header">

	
	<h1 class="port-text">Portfolio</h1>
	
</div>



<div class="container col-md-12">

	

 <div class="row port-row" style="margin-top:20px;">

	<div class="col-md-4 port-box">
		<h1>Algorithm Notebook</h1>
		<h4>React - Webpack - Node</h4>
		<a href="https://github.com/PalermoD/algorithm-viz">
			<%= image_tag "algo.jpg", :class => "img-responsive port-img"%>
		</a>
		<p>
				This is a React info page thats displays information about
				popular algorithms used in computer science. Building this site
				was pretty much a way to study and give myself a quick refrence to algorithms
		</p>
		
	</div>

	<div class="col-md-4 port-box">
		<h1>US Airport Nauticle Miles Calculator</h1>
		<h4>Javascript - jquery - Node</h4>
		<a href="https://mighty-anchorage-16808.herokuapp.com/">
			<%= image_tag "maps.png", :class => "img-responsive port-img"%>
		</a>
		<p>
				This is a javascript app that is using a node server and calls on a simple 
				api that has U.S. airport data in it. It allows you to seach any two airports in the U.S. with autocomplete and plots them on a map with route, while caculating the Nauticle miles between them
		</p>
		
	</div>
	   
	<div class="col-md-4 port-box">
		<h1>Cools</h1>
		<h4>Javascript - Angular - Node</h4>
		<a href="http://cools.com/">
			<%= image_tag "cools.png", :class => "img-responsive port-img"%>
		</a>
		<p>
		  Cools is a fasion e-comerce site that I did freelance work for on the front-end.
		  Built responsive web pages with twitter bootstrap, html. and sass. Structured handlebar templates and managed Angular client side code on the front end.
		</p>
	</div>
  
</div>


<div class="row port-row" style="margin-top:20px;">

	<div class="col-md-4 port-box">
		<h1>Youtube Search</h1>
		<h4>React - Redux - Webpack</h4>
		<a href="http://fuzzy-believe.surge.sh/">
			<%= image_tag "youtubereact.png", :class => "img-responsive port-img"%>
		</a>
		<p>
			This was a side project using youtube-api and react.js. Configured webpack, 
			built react componets to do search and play videos.  
		</p>
	</div>

	<div class="col-md-4 port-box">
		<h1>True or False </h1>
		<h4>Backbone - Sinatra</h4>
		<a href="http://truefalse.herokuapp.com/">
			<%= image_tag "backbonegame.png", :class => "img-responsive port-img"%>
		</a>
		<p>
				This is a javascript app that is using a sinatra back end and calls on a simple api I built with true and false statements. The front-end is built using a javascript client-side framwork called backbone.js
		</p>
	</div>

	<div class="col-md-4 port-box">
		<h1>Gotham24</h1>
		<h4>Ruby on Rails - Postgresql - rspec</h4>
		<a href="http://gotham.herokuapp.com/">
			<%= image_tag "gotham.png", :class => "img-responsive port-img"%>
		</a>
		<p>
				This is a social network/twitter clone built in Rouby on Rails. The app allows 
				for users to register share pictures, posts, and follow other users. The front-end is built with bootstrap and sass, the databse is postgres and is hosted on heroku.
		</p>
    </div>

</div>


<div class="row port-row" style="margin-top:20px;">
	
	

	<div class="col-md-4 port-box">
		<h1>Dezzmo</h1>
		<h4>Ruby on Rails - Postgresql</h4>
		<a href="http://www.dezzmo.com">
			<%= image_tag "dezzmo.png", :class => "img-responsive port-img"%>
		</a>
		<p>
			Dezzmo is a startup I founded In San Francisco, which is a linkedin for creative professionals. It allows users to create online portfolios, follow each other, and comment on each others work. Built in Rails and postgresql. 
		</p>
	</div>
	
	<div class="col-md-4 port-box">
		<h1>Soulster</h1>
		<h4>Ruby on Rails - Postgresql</h4>
		<a href="https://github.com/PalermoD/soulster_mvp">
			<%= image_tag "soulster.png", :class => "img-responsive port-img"%>
		</a>
		<p>
			Soulster is another side project that allows users to create their own social networks about what ever topics they like. Built in Rails and postgresql.
		</p>
	</div>

	

	<div class="col-md-4 port-box" >
		<h1>Puckermob</h1>
		<h4>PHP - Javascript - React - Mysql</h4>
		<a href="http://www.puckermob.com/">
			<%= image_tag "puckermob.png", :class => "img-responsive port-img"%>
		</a>
		<p>
		   Puckermob is an online web publisher that went through an entire rebuild
		   in lavavel. I worked through out the stack as well as optimized and manged 
		   servers. Built responsive web pages with twitter bootstrap, html. sass. Implimented 
		   react components, ui elements, and ajax calls on the front-end.
		</p>
	</div>

</div>

</div>